### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Mennaruuk** [dhhruv/YouTua#5]
How to make YouTua work with Linux? It's trying to fetch ffmpeg.exe, but of course this isn't Windows, so it isn't working. I installed `ffmpeg` using Synaptic, but even then it isn't getting recognized. These are some of the errors I'm getting:

```
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
```
```
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
```

**Comment by dhhruv** [comment]
> How to make YouTua work with Linux? It's trying to fetch ffmpeg.exe, but of course this isn't Windows, so it isn't working. I installed `ffmpeg` using Synaptic, but even then it isn't getting recognized. These are some of the errors I'm getting:
> 
> ```
> WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
> ```
> 
> ```
> WARNING: Requested formats are incompatible for merge and will be merged into mkv.
> ```

Yeah without ffmpeg it can't merge and convert those downloaded files into your preferred format so it is necessary. I read your issue and did some homework on working ffmpeg with linux so you can read this [guide 1](https://itsfoss.com/ffmpeg/) and if that doesn't work then you can read this [guide 2](https://www.tecmint.com/install-ffmpeg-in-linux/). Hope this helps.

**Comment by Mennaruuk** [comment]
I did exactly what's in the guides, but it isn't working. Not sure why, it's okay, I'll have it work over on my Windows workspace.
